name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-task-app .

      - name: Log in to Docker Hub (Optional)
        run: |
          # Replace with your Docker Hub username and password/token
          # echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image (Optional)
        run: |
          # Replace with your Docker Hub username and image name
          # docker push your-dockerhub-username/my-task-app